### ISSUE TITLE
The install process is clunky.

### ISSUE THREAD

**Issue by ijiraq** [OSSOS/liborbfit#1]
The Make process is clunky and in the end the users don't really have installed software. 

Create a package install process so that 'pip install BLAH' works.

**Comment by Mikea1985** [comment]
I believe this issue can be closed, since I installed mp_ephem using pip (and then came across this issue when investigating what the package is and where it came from).

**Comment by ijiraq** [comment]
Yes, we did manage to get pip install working.  Thanks.  I'll mark this resolved.  Should have resolved by the commit process.
