### ISSUE TITLE
trying install on python 3

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/liborbfit#3]
Trying out the brave new world. 
pip install fails with:
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
mp_ephem/__init__.py", line 2, in <module>
from bk_orbit import BKOrbit
    ModuleNotFoundError: No module named 'bk_orbit'

**Comment by mschwamb** [comment]
I'm getting the same issue with python 3 on install both with pip and installing from the source code as instructed from the repo. Any suggestions how to fix this?

**Comment by ijiraq** [comment]
Issue fixed in latest commit
