### ISSUE TITLE
mp_ephem.EphemerisReader().read seems to not work?

### ISSUE THREAD

**Issue by Mikea1985** [OSSOS/liborbfit#4]
Either mp_ephem.EphemerisReader().read is not working correctly or its purpose is not obvious. I have a plain text file with astrometry lines downloaded from the MPC. I try to read it in using

    mp_ephem.EphemerisReader().read('p1m2aZ.mpc')

but I get error message: 
>ERROR:root:Failed to parse line:      K11Uf0R \~C2013 12 05.40680 02 05 07.43 +15 36 16.0                L\~1CKy568

One copy of that error for each line in the mpc file, followed by:

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python2.7/dist-packages/mp_ephem/ephem.py", line 1359, in read
>    mpc_observation = Observation.from_string(line)
>  File "/usr/local/lib/python2.7/dist-packages/mp_ephem/ephem.py", line 606, in from_string
>    obsrec.comment = MPCComment.from_string(comment)
>AttributeError: 'NoneType' object has no attribute 'comment'

Same thing if I use

    mp_ephem.EphemerisReader('p1m2aZ.mpc')

What am I missing/doing wrong? 

Edit: I tried with the o3o08.mpc file that you have here on Github in the test/data directory: it did not give me the "ERROR:root:Failed to parse line:" errors, but still the rest of it.

**Comment by ijiraq** [comment]
Hi Mike,

I usually use this command syntax:

orb = mp_ephem.BKOrbit(None, ast_filename=’name_of_file.mpc’)

This should work on mpc downloaded files.

orb will contain an object that has the BK orbit and orb.observations will be an array containing the observations.

BUT I think what you are doing should also work so I will investigate this error and check what is going wrong.

JJ

**Comment by ijiraq** [comment]
Latest release of mp_ephem fixed this problem.
