### ISSUE TITLE
Worse satellite orbit and clock performances using binEphem.405 from 01/16/2020

### ISSUE THREAD

**Issue by darldil** [OSSOS/liborbfit#6]
Hello,

We're running a software which computes satellites' orbits and clocks, and from 01/16/2020 we've seen performances have degraded dramatically.
We believe that it is related to the 20 year block of the ASCII file that composes the binEphem.405 (from 2020 to 2040).
Did you notice something similar?

Many thanks

**Comment by ijiraq** [comment]
By 'degraded' I guess you mean the positional accuracy becomes very poor? We likely don't have the sort of precision in our positions that would be needed to notice a degradation.  The ephemeris we are using here should likely be updated to use DE430
